/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Announcement = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
});
export const LibraryInfo = IDL.Record({
  'contact' : IDL.Text,
  'hours' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
});
export const LibraryResource = IDL.Record({
  'url' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getLibraryInfo' : IDL.Func([], [LibraryInfo], ['query']),
  'getLibraryResources' : IDL.Func([], [IDL.Vec(LibraryResource)], ['query']),
  'setLibraryInfo' : IDL.Func([LibraryInfo], [], []),
  'setLibraryResources' : IDL.Func([IDL.Vec(LibraryResource)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Announcement = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
  });
  const LibraryInfo = IDL.Record({
    'contact' : IDL.Text,
    'hours' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
  });
  const LibraryResource = IDL.Record({
    'url' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getLibraryInfo' : IDL.Func([], [LibraryInfo], ['query']),
    'getLibraryResources' : IDL.Func([], [IDL.Vec(LibraryResource)], ['query']),
    'setLibraryInfo' : IDL.Func([LibraryInfo], [], []),
    'setLibraryResources' : IDL.Func([IDL.Vec(LibraryResource)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };